// Package "issue185" provides primitives to interact with the AsyncAPI specification.
//
// Code generated by github.com/lerenn/asyncapi-codegen version (devel) DO NOT EDIT.
package issue185

import (
	"fmt"
	"time"
)

// AsyncAPIVersion is the version of the used AsyncAPI document
const AsyncAPIVersion = ""

// MessageWithCorrelationID is implemented by messages that carry a correlation ID.
type MessageWithCorrelationID interface {
	CorrelationID() string
	SetCorrelationID(id string)
}

// Error is the error structure returned by the controller operations.
type Error struct {
	Channel string
	Err     error
}

// Error returns a string representation of the error.
func (e *Error) Error() string {
	return fmt.Sprintf("channel %q: err %v", e.Channel, e.Err)
}

// BaseEventSchema is a schema from the AsyncAPI specification required in messages
type BaseEventSchema struct {
	Time time.Time `json:"time"`
}

// BaseEventInfoSchema is a schema from the AsyncAPI specification required in messages
type BaseEventInfoSchema struct {
	Data ContentDataSchema `json:"data"`
}

// ContentDataSchema is a schema from the AsyncAPI specification required in messages
type ContentDataSchema struct {
	ContentId string `json:"contentId"`
}

// EventPayloadSchema is a schema from the AsyncAPI specification required in messages
type EventPayloadSchema struct {
	Data ContentDataSchema `json:"data"`
	Id   string            `json:"id"`
	Time time.Time         `json:"time"`
}
