// Package "issue258" provides primitives to interact with the AsyncAPI specification.
//
// Code generated by github.com/lerenn/asyncapi-codegen version (devel) DO NOT EDIT.
package issue258

import (
	"encoding/json"
	"fmt"

	"github.com/lerenn/asyncapi-codegen/pkg/extensions"
)

// AsyncAPIVersion is the version of the used AsyncAPI document
const AsyncAPIVersion = "1.0.0"

type MessageWithCorrelationID interface {
	CorrelationID() string
	SetCorrelationID(id string)
}

type Error struct {
	Channel string
	Err     error
}

func (e *Error) Error() string {
	return fmt.Sprintf("channel %q: err %v", e.Channel, e.Err)
}

// Message 'TestMessageMessageFromTestChannel' reference another one at '#/components/messages/testMessage'.
// This should be fixed in a future version to allow message override.
// If you encounter this message, feel free to open an issue on this subject
// to let know that you need this functionnality.

// TestMessageMessagePayload is a schema from the AsyncAPI specification required in messages
type TestMessageMessagePayload struct {
	// WARNING: only one of the following fields must be set
	IntValueSchema *IntValueSchema `json:"-"`
	StrValueSchema *StrValueSchema `json:"-"`
}

// MarshalJSON marshals the oneOf schema, emitting the single member that is set.
func (t TestMessageMessagePayload) MarshalJSON() ([]byte, error) {
	if t.IntValueSchema != nil {
		return json.Marshal(t.IntValueSchema)
	}
	if t.StrValueSchema != nil {
		return json.Marshal(t.StrValueSchema)
	}

	return []byte("null"), nil
}

// UnmarshalJSON unmarshals JSON into the first oneOf member that accepts it.
// Without a discriminator, members are tried in order; the first one that
// unmarshals without error wins.
func (t *TestMessageMessagePayload) UnmarshalJSON(data []byte) error {
	{
		var value IntValueSchema
		if err := json.Unmarshal(data, &value); err == nil {
			t.IntValueSchema = &value
			return nil
		}
	}
	{
		var value StrValueSchema
		if err := json.Unmarshal(data, &value); err == nil {
			t.StrValueSchema = &value
			return nil
		}
	}

	return fmt.Errorf("data did not match any schema in oneOf")
}

// TestMessageMessage is the message expected for 'TestMessageMessage' channel.
type TestMessageMessage struct {
	// Payload will be inserted in the message payload
	Payload TestMessageMessagePayload
}

func NewTestMessageMessage() TestMessageMessage {
	var msg TestMessageMessage

	return msg
}

// brokerMessageToTestMessageMessage will fill a new TestMessageMessage with data from generic broker message
func brokerMessageToTestMessageMessage(bMsg extensions.BrokerMessage) (TestMessageMessage, error) {
	var msg TestMessageMessage

	// Unmarshal payload to expected message payload format
	err := json.Unmarshal(bMsg.Payload, &msg.Payload)
	if err != nil {
		return msg, err
	}

	// TODO: run checks on msg type

	return msg, nil
}

// toBrokerMessage will generate a generic broker message from TestMessageMessage data
func (msg TestMessageMessage) toBrokerMessage() (extensions.BrokerMessage, error) {
	// TODO: implement checks on message

	// Marshal payload to JSON
	payload, err := json.Marshal(msg.Payload)
	if err != nil {
		return extensions.BrokerMessage{}, err
	}

	// There is no headers here
	headers := make(map[string][]byte, 0)

	return extensions.BrokerMessage{
		Headers: headers,
		Payload: payload,
	}, nil
}

// IntValueSchema is a schema from the AsyncAPI specification required in messages
type IntValueSchema struct {
	Value *int64 `json:"value,omitempty"`
}

// StrValueSchema is a schema from the AsyncAPI specification required in messages
type StrValueSchema struct {
	Value *string `json:"value,omitempty"`
}

const (
	// TestChannelPath is the constant representing the 'TestChannel' channel path.
	TestChannelPath = "v3.issue258.test"
)

// ChannelsPaths is an array of all channels paths
var ChannelsPaths = []string{
	TestChannelPath,
}
