# More infos: https://golangci-lint.run/usage/linters/
linters:
  enable:
    - cyclop
    - dupword
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocyclo
    - godot
    - gofmt
    - goimports
    - ireturn
    - lll
    - maintidx
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - revive
    - stylecheck
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments
