# More infos: https://golangci-lint.run/usage/linters/
linters:
  enable:
    - dupword
    - errorlint
    - exhaustive
    - exportloopref
    - goconst
    - gocyclo
    - godot
    - gofmt
    - goimports
    - misspell
    - nakedret
    - nilerr
    - revive
    - stylecheck
    - thelper
    - unconvert
    - unparam
    - whitespace

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments
