services:
  # NATS variants
  nats:
    image: nats:latest
    ports:
      - 4222:4222
    expose:
      - 4222
  nats-tls:
    image: nats:latest
    ports:
      - "4223:4222"
    expose:
      - 4223
    command: [
      "--tls",
      "--tlscert", "/certs/server-cert.pem",
      "--tlskey", "/certs/server-key.pem",
    ]
    volumes:
      - ./tmp/certs/nats:/certs
  nats-tls-basic-auth:
    image: nats:latest
    ports:
      - 4224:4222
    expose:
      - 4224
    command: [
      "--tls",
      "--tlscert", "/certs/server-cert.pem",
      "--tlskey", "/certs/server-key.pem",
      "--user", "user",
      "--pass", "password",
    ]
    volumes:
      - ./tmp/certs/nats:/certs
  
  # NATS Jetstream variants
  nats-jetstream:
    image: nats:latest
    ports:
      - 4225:4222
    expose:
      - 4225
    command: [
      "-js",
    ]
  nats-jetstream-tls:
    image: nats:latest
    ports:
      - 4226:4222
    expose:
      - 4226
    command: [
      "-js",
      "--tls",
      "--tlscert", "/certs/server-cert.pem",
      "--tlskey", "/certs/server-key.pem",
    ]
    volumes:
      - ./tmp/certs/nats:/certs
  nats-jetstream-tls-basic-auth:
    image: nats:latest
    ports:
      - 4227:4222
    expose:
      - 4227
    command: [
      "-js",
      "--tls",
      "--tlscert", "/certs/server-cert.pem",
      "--tlskey", "/certs/server-key.pem",
      "--user", "user",
      "--pass", "password",
    ]
    volumes:
      - ./tmp/certs/nats:/certs

  # Kafka variants
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: "AAAAAAAAAAAAAAAAAAAAAA"
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - ./tmp/kafka-kraft/kafka:/var/lib/kafka/data
  kafka-tls:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka-tls
    container_name: kafka-tls
    ports:
      - "9094:9094"
    environment:
      CLUSTER_ID: "AAAAAAAAAAAAAAAAAAAAAA"
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka-tls:29093"
      KAFKA_LISTENERS: "SSL://kafka-tls:29092,CONTROLLER://kafka-tls:29093,SSL_HOST://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "SSL://kafka-tls:29092,SSL_HOST://localhost:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,SSL:SSL,SSL_HOST:SSL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "SSL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_TYPE: JKS
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.keystore.jks.password
      KAFKA_SSL_KEY_CREDENTIALS: kafka.keystore.jks.password
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.keystore.jks
      KAFKA_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.keystore.jks.password
      KAFKA_SSL_CLIENT_AUTH: "none"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
    volumes:
      - ./tmp/certs/kafka:/etc/kafka/secrets
      - ./tmp/kafka-kraft/kafka-tls:/var/lib/kafka/data
  kafka-tls-basic-auth:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka-tls-basic-auth
    container_name: kafka-tls-basic-auth
    ports:
      - "9096:9096"
    environment:
      CLUSTER_ID: "AAAAAAAAAAAAAAAAAAAAAA"
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka-tls-basic-auth:29093"
      KAFKA_LISTENERS: "SASL_SSL://kafka-tls-basic-auth:29092,CONTROLLER://kafka-tls-basic-auth:29093,SASL_SSL_HOST://0.0.0.0:9096"
      KAFKA_ADVERTISED_LISTENERS: "SASL_SSL://kafka-tls-basic-auth:29092,SASL_SSL_HOST://localhost:9096"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,SASL_SSL:SASL_SSL,SASL_SSL_HOST:SASL_SSL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "SASL_SSL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_TYPE: JKS
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.keystore.jks.password
      KAFKA_SSL_KEY_CREDENTIALS: kafka.keystore.jks.password
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.keystore.jks
      KAFKA_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.keystore.jks.password
      KAFKA_SSL_CLIENT_AUTH: "none"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM-SHA-512
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
    volumes:
      - ./tmp/certs/kafka:/etc/kafka/secrets
      - ./tmp/kafka-kraft/kafka-tls-basic-auth:/var/lib/kafka/data
      - ./config/kafka-tls-basic-auth/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./config/kafka-tls-basic-auth/client.properties:/etc/kafka/client.properties
    
  