version: "3.5"

services:
  app:
    image: golang:1.19.4
    volumes:
      - gocache:/go/pkg/mod
      - gobuild:/root/.cache/go-build
      - ../../../:/go/asyncapi-codegen
    working_dir: /go/asyncapi-codegen
    command: go run ./examples/helloworld/nats/app
    networks:
      - brokers
  user:
    depends_on:
      - app
    image: golang:1.19.4
    volumes:
      - gocache:/go/pkg/mod
      - gobuild:/root/.cache/go-build
      - ../../../:/go/asyncapi-codegen
    working_dir: /go/asyncapi-codegen
    command: go run ./examples/helloworld/nats/user
    networks:
      - brokers

volumes:
  gocache:
  gobuild:

networks:
  brokers:
    name: asyncapi-codegen_brokers
    external: true
