// Package "issue137" provides primitives to interact with the AsyncAPI specification.
//
// Code generated by github.com/lerenn/asyncapi-codegen version (devel) DO NOT EDIT.
package issue137

import (
	"fmt"
)

// AsyncAPIVersion is the version of the used AsyncAPI document
const AsyncAPIVersion = ""

// MessageWithCorrelationID is implemented by messages that carry a correlation ID.
type MessageWithCorrelationID interface {
	CorrelationID() string
	SetCorrelationID(id string)
}

// Error is the error structure returned by the controller operations.
type Error struct {
	Channel string
	Err     error
}

// Error returns a string representation of the error.
func (e *Error) Error() string {
	return fmt.Sprintf("channel %q: err %v", e.Channel, e.Err)
}

// AuditSchema is a schema from the AsyncAPI specification required in messages
// Description: An audit event is a record of an event that has occurred in a system.
type AuditSchema struct {
	Channel ChannelSchema `json:"channel" validate:"oneof='API0' 'API1' 'API2' 'API3' 'API4'"`
}

// ChannelSchema is a schema from the AsyncAPI specification required in messages
type ChannelSchema string
