package middleware

import "context"

// Middleware is the signature of the function that needs to be implemented to use
// middleware functionnality
//
// You can call the next middleware during the execution of the defined middleware
// in order to wrap code execution (for example, to time execution, or recover in
// case of panic).
type Middleware func(ctx context.Context, next Next) context.Context

// Next represents the next middleware that can be executed during the
// previous middleware. If this is already the last middleware, it will execute
// the appropriate autogenerated code for reception/sending of messages.
type Next func(ctx context.Context)
