version: "3.5"

services:
  server:
    image: golang:1.19.4
    volumes:
      - gocache:/go/pkg/mod
      - gobuild:/root/.cache/go-build
      - ../../../:/go/asyncapi-codegen
    working_dir: /go/asyncapi-codegen
    command: go run ./examples/ping/nats/server
    networks:
      - brokers
  client:
    depends_on:
      - server
    image: golang:1.19.4
    volumes:
      - gocache:/go/pkg/mod
      - gobuild:/root/.cache/go-build
      - ../../../:/go/asyncapi-codegen
    working_dir: /go/asyncapi-codegen
    command: go run ./examples/ping/nats/client
    networks:
      - brokers

volumes:
  gocache:
  gobuild:

networks:
  brokers:
    name: asyncapi-codegen_brokers
    external: true
