version: '3.5'

services:
  server:
    image: golang:1.20.5
    volumes:
      - gocache:/go/pkg/mod
      - gobuild:/root/.cache/go-build
      - ../../../:/go/asyncapi-codegen
    working_dir: /go/asyncapi-codegen
    command: go run ./examples/ping/kafka/server
    networks:
      - brokers
  client:
    depends_on:
      - server
    image: golang:1.20.5
    volumes:
      - gocache:/go/pkg/mod
      - gobuild:/root/.cache/go-build
      - ../../../:/go/asyncapi-codegen
    working_dir: /go/asyncapi-codegen
    command: go run ./examples/ping/kafka/client
    networks:
      - brokers

volumes:
  gocache:
  gobuild:

networks:
  brokers:
    name: asyncapi-codegen_brokers
    external: true
