security.protocol=SASL_SSL
ssl.truststore.location=/etc/kafka/secrets/kafka.keystore.jks
ssl.truststore.password=changeit
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";

