// Package "issue135" provides primitives to interact with the AsyncAPI specification.
//
// Code generated by github.com/lerenn/asyncapi-codegen version (devel) DO NOT EDIT.
package issue135

import (
	"fmt"
)

// AsyncAPIVersion is the version of the used AsyncAPI document
const AsyncAPIVersion = "1.2.3"

type MessageWithCorrelationID interface {
	CorrelationID() string
	SetCorrelationID(id string)
}

type Error struct {
	Channel string
	Err     error
}

func (e *Error) Error() string {
	return fmt.Sprintf("channel %q: err %v", e.Channel, e.Err)
}

const (
	// GroupChannelPath is the constant representing the 'GroupChannel' channel path.
	GroupChannelPath = "v3.issue135.group"
	// InfoChannelPath is the constant representing the 'InfoChannel' channel path.
	InfoChannelPath = "v3.issue135.info"
	// ProjectChannelPath is the constant representing the 'ProjectChannel' channel path.
	ProjectChannelPath = "v3.issue135.project"
	// ResourceChannelPath is the constant representing the 'ResourceChannel' channel path.
	ResourceChannelPath = "v3.issue135.resource"
	// StatusChannelPath is the constant representing the 'StatusChannel' channel path.
	StatusChannelPath = "v3.issue135.status"
)

// ChannelsPaths is an array of all channels paths
var ChannelsPaths = []string{
	GroupChannelPath,
	InfoChannelPath,
	ProjectChannelPath,
	ResourceChannelPath,
	StatusChannelPath,
}
