// Package "asyncapi" provides primitives to interact with the AsyncAPI specification.
//
// Code generated by github.com/lerenn/asyncapi-codegen version (devel) DO NOT EDIT.
package asyncapi

import (
	"log"

	"encoding/json"
	"github.com/google/uuid"
)

// AppSubscriber represents all application handlers that are expecting messages from clients
type AppSubscriber interface {
	// UserDelete
	UserDelete(msg UserDeleteMessage)

	// UserModify
	UserModify(msg UserModifyExtraWordingMessage)
}

// AppController is the structure that provides publishing capabilities to the
// developer and and connect the broker with the app
type AppController struct {
	brokerController BrokerController
	stopSubscribers  map[string]chan interface{}
}

// NewAppController links the application to the broker
func NewAppController(bs BrokerController) *AppController {
	// TODO: Check that brokerController is not nil

	return &AppController{
		brokerController: bs,
		stopSubscribers:  make(map[string]chan interface{}),
	}
}

// SubscribeAll will subscribe to channels on which the app is expecting messages
func (ac *AppController) SubscribeAll(as AppSubscriber) error {
	// TODO: Check that as is not nil

	if err := ac.SubscribeUserDelete(as.UserDelete); err != nil {
		return err
	}
	if err := ac.SubscribeUserModify(as.UserModify); err != nil {
		return err
	}

	return nil
}

// UnsubscribeAll will unsubscribe all remaining subscribed channels
func (ac *AppController) UnsubscribeAll() {
	ac.UnsubscribeUserDelete()
	ac.UnsubscribeUserModify()
}

// SubscribeUserDelete will subscribe to new messages from 'user/delete' channel
func (ac *AppController) SubscribeUserDelete(fn func(msg UserDeleteMessage)) error {
	// Subscribe to broker channel
	msgs, stop, err := ac.brokerController.Subscribe("user/delete")
	if err != nil {
		return err
	}

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		var msg struct {
			// Payload will be inserted in the message payload
			Payload int64
		}
		var um UniversalMessage

		for open := true; open; {
			um, open = <-msgs

			err := json.Unmarshal(um.Payload, &msg)
			if err != nil {
				log.Println("an error happened when receiving an event:", err) // TODO: add proper error handling
				continue
			}

			// TODO: run checks on msg type

			fn(msg)
		}
	}()

	// Add the stop channel to the inside map
	ac.stopSubscribers["user/delete"] = stop

	return nil
}

// UnsubscribeUserDelete will unsubscribe messages from 'user/delete' channel
func (ac *AppController) UnsubscribeUserDelete() {
	stopChan, exists := ac.stopSubscribers["user/delete"]
	if !exists {
		return
	}

	stopChan <- true
	delete(ac.stopSubscribers, "user/delete")
} // SubscribeUserModify will subscribe to new messages from 'user/modify' channel
func (ac *AppController) SubscribeUserModify(fn func(msg UserModifyExtraWordingMessage)) error {
	// Subscribe to broker channel
	msgs, stop, err := ac.brokerController.Subscribe("user/modify")
	if err != nil {
		return err
	}

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		var msg UserModifyExtraWordingMessage
		var um UniversalMessage

		for open := true; open; {
			um, open = <-msgs

			err := json.Unmarshal(um.Payload, &msg)
			if err != nil {
				log.Println("an error happened when receiving an event:", err) // TODO: add proper error handling
				continue
			}

			// TODO: run checks on msg type

			fn(msg)
		}
	}()

	// Add the stop channel to the inside map
	ac.stopSubscribers["user/modify"] = stop

	return nil
}

// UnsubscribeUserModify will unsubscribe messages from 'user/modify' channel
func (ac *AppController) UnsubscribeUserModify() {
	stopChan, exists := ac.stopSubscribers["user/modify"]
	if !exists {
		return
	}

	stopChan <- true
	delete(ac.stopSubscribers, "user/modify")
}

// Close will clean up any existing resources on the controller
func (ac *AppController) Close() {
	ac.UnsubscribeAll()
}

// PublishUserSignedin will publish messages to 'user/signedin' channel
func (ac *AppController) PublishUserSignedin(msg UserSignedinMessage) error {
	// TODO: check that 'ac' is not nil
	// TODO: implement checks on message

	// Convert to JSON payload
	payload, err := json.Marshal(msg.Payload)
	if err != nil {
		return err
	}

	// Create universal message
	um := UniversalMessage{
		Payload: payload,
	}

	// Publish on event broker
	return ac.brokerController.Publish("user/signedin", um)
}

// PublishUserSignedup will publish messages to 'user/signedup' channel
func (ac *AppController) PublishUserSignedup(msg UserSignedUpExtraWordingMessage) error {
	// TODO: check that 'ac' is not nil
	// TODO: implement checks on message

	// Convert to JSON payload
	payload, err := json.Marshal(msg.Payload)
	if err != nil {
		return err
	}

	// Create a new correlationID if none is specified
	correlationID := uuid.New().String()
	// TODO: get if from another place according to spec
	if msg.Headers.CorrelationID != "" {
		correlationID = msg.Headers.CorrelationID
	}

	// Create universal message
	um := UniversalMessage{
		Payload:       payload,
		CorrelationID: correlationID,
	}

	// Publish on event broker
	return ac.brokerController.Publish("user/signedup", um)
}

// Listen will let the controller handle subscriptions and will be interrupted
// only when an struct is sent on the interrupt channel
func (ac *AppController) Listen(irq chan interface{}) {
	<-irq
}

// ClientSubscriber represents all application handlers that are expecting messages from application
type ClientSubscriber interface {
	// UserSignedin
	UserSignedin(msg UserSignedinMessage)

	// UserSignedup
	UserSignedup(msg UserSignedUpExtraWordingMessage)
}

// ClientController is the structure that provides publishing capabilities to the
// developer and and connect the broker with the client
type ClientController struct {
	brokerController BrokerController
	stopSubscribers  map[string]chan interface{}
}

// NewClientController links the client to the broker
func NewClientController(bs BrokerController) *ClientController {
	// TODO: Check that brokerController is not nil

	return &ClientController{
		brokerController: bs,
		stopSubscribers:  make(map[string]chan interface{}),
	}
}

// SubscribeAll will subscribe to channels on which the client is expecting messages
func (cc *ClientController) SubscribeAll(cs ClientSubscriber) error {
	// TODO: Check that cs is not nil

	if err := cc.SubscribeUserSignedin(cs.UserSignedin); err != nil {
		return err
	}
	if err := cc.SubscribeUserSignedup(cs.UserSignedup); err != nil {
		return err
	}

	return nil
}

// UnsubscribeAll will unsubscribe all remaining subscribed channels
func (cc *ClientController) UnsubscribeAll() {
	cc.UnsubscribeUserSignedin()
	cc.UnsubscribeUserSignedup()
}

// SubscribeUserSignedin will subscribe to new messages from 'user/signedin' channel
func (cc *ClientController) SubscribeUserSignedin(fn func(msg UserSignedinMessage)) error {
	// Subscribe to broker channel
	msgs, stop, err := cc.brokerController.Subscribe("user/signedin")
	if err != nil {
		return err
	}

	// Asynchronously listen to new messages and pass them to client subscriber
	go func() {
		var msg struct {
			// Payload will be inserted in the message payload
			Payload int64
		}
		var um UniversalMessage

		for open := true; open; {
			um, open = <-msgs

			err := json.Unmarshal(um.Payload, &msg)
			if err != nil {
				log.Println("an error happened when receiving an event:", err) // TODO: add proper error handling
				continue
			}

			// TODO: run checks on data type

			fn(msg)
		}
	}()

	// Add the stop channel to the inside map
	cc.stopSubscribers["user/signedin"] = stop

	return nil
}

// UnsubscribeUserSignedin will unsubscribe messages from 'user/signedin' channel
func (cc *ClientController) UnsubscribeUserSignedin() {
	stopChan, exists := cc.stopSubscribers["user/signedin"]
	if !exists {
		return
	}

	stopChan <- true
	delete(cc.stopSubscribers, "user/signedin")
}

// SubscribeUserSignedup will subscribe to new messages from 'user/signedup' channel
func (cc *ClientController) SubscribeUserSignedup(fn func(msg UserSignedUpExtraWordingMessage)) error {
	// Subscribe to broker channel
	msgs, stop, err := cc.brokerController.Subscribe("user/signedup")
	if err != nil {
		return err
	}

	// Asynchronously listen to new messages and pass them to client subscriber
	go func() {
		var msg UserSignedUpExtraWordingMessage
		var um UniversalMessage

		for open := true; open; {
			um, open = <-msgs

			err := json.Unmarshal(um.Payload, &msg)
			if err != nil {
				log.Println("an error happened when receiving an event:", err) // TODO: add proper error handling
				continue
			}

			// TODO: run checks on data type

			fn(msg)
		}
	}()

	// Add the stop channel to the inside map
	cc.stopSubscribers["user/signedup"] = stop

	return nil
}

// UnsubscribeUserSignedup will unsubscribe messages from 'user/signedup' channel
func (cc *ClientController) UnsubscribeUserSignedup() {
	stopChan, exists := cc.stopSubscribers["user/signedup"]
	if !exists {
		return
	}

	stopChan <- true
	delete(cc.stopSubscribers, "user/signedup")
}

// Close will clean up any existing resources on the controller
func (cc *ClientController) Close() {
	cc.UnsubscribeAll()
}

// PublishUserDelete will publish messages to 'user/delete' channel
func (cc *ClientController) PublishUserDelete(msg UserDeleteMessage) error {
	// TODO: check that 'cc' is not nil
	// TODO: implement checks on message

	// Convert to JSON payload
	payload, err := json.Marshal(msg.Payload)
	if err != nil {
		return err
	}

	// Create universal message
	um := UniversalMessage{
		Payload: payload,
	}

	// Publish on event broker
	return cc.brokerController.Publish("user/delete", um)
}

// PublishUserModify will publish messages to 'user/modify' channel
func (cc *ClientController) PublishUserModify(msg UserModifyExtraWordingMessage) error {
	// TODO: check that 'cc' is not nil
	// TODO: implement checks on message

	// Convert to JSON payload
	payload, err := json.Marshal(msg.Payload)
	if err != nil {
		return err
	}

	// Create universal message
	um := UniversalMessage{
		Payload: payload,
	}

	// Publish on event broker
	return cc.brokerController.Publish("user/modify", um)
}

const (
	// CorrelationIDField is the name of the field that will contain the correlation ID
	CorrelationIDField = "correlation_id"
)

// UniversalMessage is a wrapper that will contain all information regarding a message
type UniversalMessage struct {
	CorrelationID string
	Payload       []byte
}

// BrokerController represents the functions that should be implemented to connect
// the broker to the application or the client
type BrokerController interface {
	// Publish a message to the broker
	Publish(channel string, mw UniversalMessage) error

	// Subscribe to messages from the broker
	Subscribe(channel string) (msgs chan UniversalMessage, stop chan interface{}, err error)
}

// UserDelete
type UserDeleteMessage struct {
	// Payload will be inserted in the message payload
	Payload int64
}

// UserSignedin
type UserSignedinMessage struct {
	// Payload will be inserted in the message payload
	Payload int64
}

// UserModifyExtraWording
type UserModifyExtraWordingMessage struct {
	// Payload will be inserted in the message payload
	Payload struct {
		// Name
		Name string `json:"name"`
	}
}

// UserSignedUpExtraWording
type UserSignedUpExtraWordingMessage struct {
	// Headers will be used to fill the message headers
	Headers struct {
		// CorrelationID
		CorrelationID string `json:"correlation_id"`
	}

	// Payload will be inserted in the message payload
	Payload struct {
		// Name of the user
		DisplayName string `json:"display_name"`

		// Email of the user
		Email string `json:"email"`

		// Schema
		Schema SchemaStruct `json:"schema"`
	}
}

// UserSignedUpExtraWording
type UserSignedUpExtraWording string

// Limit
type Limit int32

// Number
type Number float64

// Number32
type Number32 float32

// Number64
type Number64 float64

// SchemaStruct
type SchemaStruct string

// Total
type Total int64
