// Package "issue333" provides primitives to interact with the AsyncAPI specification.
//
// Code generated by github.com/lerenn/asyncapi-codegen version (devel) DO NOT EDIT.
package issue333

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"sync"

	"github.com/go-playground/validator/v10"
	"github.com/lerenn/asyncapi-codegen/pkg/extensions"
)

// validate is the validator used to discriminate between the several message
// types that can be received on a single channel (issue #333).
var validate = validator.New()

// messageDispatchHandler tries to convert and validate a raw broker message
// against a single expected message type and, when it matches, dispatches it to
// the registered callback. It returns true when the message matched the type.
type messageDispatchHandler func(ctx context.Context, bMsg extensions.BrokerMessage) (handled bool, err error)

// messageDispatcher holds, per channel address, the per-message handlers
// registered by multi-message receive subscriptions and multiplexes a single
// broker subscription to them (issue #333). It is held by pointer on the
// controller so the controller stays safe to copy by value.
type messageDispatcher struct {
	// mutex protects concurrent access to handlers.
	mutex sync.Mutex
	// handlers maps a channel address to the per-message handlers registered on it.
	handlers map[string]map[string]messageDispatchHandler
}

// controller is the controller that will be used to communicate with the broker
// It will be used internally by AppController and UserController
type controller struct {
	// broker is the broker controller that will be used to communicate
	broker extensions.BrokerController
	// subscriptions is a map of all subscriptions
	subscriptions map[string]extensions.BrokerChannelSubscription
	// dispatcher multiplexes broker messages to the per-message handlers
	// registered by multi-message receive subscriptions (issue #333).
	dispatcher *messageDispatcher
	// logger is the logger that will be used to log operations on controller
	logger extensions.Logger
	// middlewares are the middlewares that will be executed when sending or
	// receiving messages
	middlewares []extensions.Middleware
	// handler to handle errors from consumers and middlewares
	errorHandler extensions.ErrorHandler
}

// ControllerOption is the type of the options that can be passed
// when creating a new Controller
type ControllerOption func(controller *controller)

// WithLogger attaches a logger to the controller
func WithLogger(logger extensions.Logger) ControllerOption {
	return func(controller *controller) {
		controller.logger = logger
	}
}

// WithMiddlewares attaches middlewares that will be executed when sending or receiving messages
func WithMiddlewares(middlewares ...extensions.Middleware) ControllerOption {
	return func(controller *controller) {
		controller.middlewares = middlewares
	}
}

// WithErrorHandler attaches a errorhandler to handle errors from subscriber functions
func WithErrorHandler(handler extensions.ErrorHandler) ControllerOption {
	return func(controller *controller) {
		controller.errorHandler = handler
	}
}

// AppSubscriber contains all handlers that are listening messages for App
type AppSubscriber interface {
	// ReceiveEventsOperationForUserDeletedReceived receive all UserDeleted messages from Events channel.
	ReceiveEventsOperationForUserDeletedReceived(ctx context.Context, msg UserDeletedMessage) error

	// ReceiveEventsOperationForUserSignedUpReceived receive all UserSignedUp messages from Events channel.
	ReceiveEventsOperationForUserSignedUpReceived(ctx context.Context, msg UserSignedUpMessage) error
}

// AppController is the structure that provides sending capabilities to the
// developer and and connect the broker with the App
type AppController struct {
	controller
}

// NewAppController links the App to the broker
func NewAppController(bc extensions.BrokerController, options ...ControllerOption) (*AppController, error) {
	// Check if broker controller has been provided
	if bc == nil {
		return nil, extensions.ErrNilBrokerController
	}

	// Create default controller
	controller := controller{
		broker:        bc,
		subscriptions: make(map[string]extensions.BrokerChannelSubscription),
		dispatcher:    &messageDispatcher{handlers: make(map[string]map[string]messageDispatchHandler)},
		logger:        extensions.DummyLogger{},
		middlewares:   make([]extensions.Middleware, 0),
		errorHandler:  extensions.DefaultErrorHandler(),
	}

	// Apply options
	for _, option := range options {
		option(&controller)
	}

	return &AppController{controller: controller}, nil
}

func (c AppController) wrapMiddlewares(
	middlewares []extensions.Middleware,
	callback extensions.NextMiddleware,
) func(ctx context.Context, msg *extensions.BrokerMessage) error {
	var called bool

	// If there is no more middleware
	if len(middlewares) == 0 {
		return func(ctx context.Context, msg *extensions.BrokerMessage) error {
			// Call the callback if it exists and it has not been called already
			if callback != nil && !called {
				called = true
				return callback(ctx)
			}

			// Nil can be returned, as the callback has already been called
			return nil
		}
	}

	// Get the next function to call from next middlewares or callback
	next := c.wrapMiddlewares(middlewares[1:], callback)

	// Wrap middleware into a check function that will call execute the middleware
	// and call the next wrapped middleware if the returned function has not been
	// called already
	return func(ctx context.Context, msg *extensions.BrokerMessage) error {
		// Call the middleware and the following if it has not been done already
		if !called {
			// Create the next call with the context and the message
			nextWithArgs := func(ctx context.Context) error {
				return next(ctx, msg)
			}

			// Call the middleware and register it as already called
			called = true
			if err := middlewares[0](ctx, msg, nextWithArgs); err != nil {
				return err
			}

			// If next has already been called in middleware, it should not be executed again
			return nextWithArgs(ctx)
		}

		// Nil can be returned, as the next middleware has already been called
		return nil
	}
}

func (c AppController) executeMiddlewares(ctx context.Context, msg *extensions.BrokerMessage, callback extensions.NextMiddleware) error {
	// Wrap middleware to have 'next' function when calling them
	wrapped := c.wrapMiddlewares(c.middlewares, callback)

	// Execute wrapped middlewares
	return wrapped(ctx, msg)
}

func addAppContextValues(ctx context.Context, addr string) context.Context {
	ctx = context.WithValue(ctx, extensions.ContextKeyIsVersion, "1.0.0")
	ctx = context.WithValue(ctx, extensions.ContextKeyIsProvider, "app")
	return context.WithValue(ctx, extensions.ContextKeyIsChannel, addr)
}

// Close will clean up any existing resources on the controller
func (c *AppController) Close(ctx context.Context) {
	// Unsubscribing remaining channels
	c.UnsubscribeFromAllChannels(ctx)

	c.logger.Info(ctx, "Closed app controller", extensions.LogInfosFromContext(ctx)...)
}

// SubscribeToAllChannels will receive messages from channels where channel has
// no parameter on which the app is expecting messages. For channels with parameters,
// they should be subscribed independently.
func (c *AppController) SubscribeToAllChannels(ctx context.Context, as AppSubscriber) error {
	if as == nil {
		return extensions.ErrNilAppSubscriber
	}

	if err := c.SubscribeToReceiveEventsOperationForUserDeleted(ctx, as.ReceiveEventsOperationForUserDeletedReceived); err != nil {
		return err
	}
	if err := c.SubscribeToReceiveEventsOperationForUserSignedUp(ctx, as.ReceiveEventsOperationForUserSignedUpReceived); err != nil {
		return err
	}

	return nil
}

// UnsubscribeFromAllChannels will stop the subscription of all remaining subscribed channels
func (c *AppController) UnsubscribeFromAllChannels(ctx context.Context) {
	c.UnsubscribeFromReceiveEventsOperationForUserDeleted(ctx)
	c.UnsubscribeFromReceiveEventsOperationForUserSignedUp(ctx)
}

// SubscribeToReceiveEventsOperationForUserDeleted will receive UserDeleted messages from Events channel.
//
// Callback function 'fn' will be called each time a UserDeleted message is received.
//
// NOTE: this channel carries several message types; a received message is only
// dispatched to this callback when it matches the UserDeletedMessage schema.
func (c *AppController) SubscribeToReceiveEventsOperationForUserDeleted(
	ctx context.Context,
	fn func(ctx context.Context, msg UserDeletedMessage) error,
) error {
	// Get channel address
	addr := "v3.issue333.events"

	// Set context
	ctx = addAppContextValues(ctx, addr)
	ctx = context.WithValue(ctx, extensions.ContextKeyIsDirection, "reception")

	// Build the handler that discriminates UserDeletedMessage messages and
	// dispatches them to the callback.
	handler := func(hdlrCtx context.Context, bMsg extensions.BrokerMessage) (bool, error) {
		// Try to convert the broker message to the expected type
		msg, err := brokerMessageToUserDeletedMessage(bMsg)
		if err != nil {
			return false, nil
		}

		// Validate it against the message schema to discriminate it from the
		// other message types received on this channel.
		if err := validate.Struct(msg); err != nil {
			return false, nil
		}

		// Execute the subscription function
		if err := fn(hdlrCtx, msg); err != nil {
			return true, err
		}

		return true, nil
	}

	// Register the handler and subscribe to the channel if not done already
	return c.subscribeToReceiveEventsOperation(ctx, addr, "UserDeletedMessage", handler)
}

// UnsubscribeFromReceiveEventsOperationForUserDeleted will stop the reception of UserDeleted messages from Events channel.
// The underlying broker subscription is canceled once the last message type on
// the channel is unsubscribed.
// A timeout can be set in context to avoid blocking operation, if needed.
func (c *AppController) UnsubscribeFromReceiveEventsOperationForUserDeleted(
	ctx context.Context,
) {
	// Get channel address
	addr := "v3.issue333.events"

	c.unsubscribeFromReceiveEventsOperation(ctx, addr, "UserDeletedMessage")
}

// SubscribeToReceiveEventsOperationForUserSignedUp will receive UserSignedUp messages from Events channel.
//
// Callback function 'fn' will be called each time a UserSignedUp message is received.
//
// NOTE: this channel carries several message types; a received message is only
// dispatched to this callback when it matches the UserSignedUpMessage schema.
func (c *AppController) SubscribeToReceiveEventsOperationForUserSignedUp(
	ctx context.Context,
	fn func(ctx context.Context, msg UserSignedUpMessage) error,
) error {
	// Get channel address
	addr := "v3.issue333.events"

	// Set context
	ctx = addAppContextValues(ctx, addr)
	ctx = context.WithValue(ctx, extensions.ContextKeyIsDirection, "reception")

	// Build the handler that discriminates UserSignedUpMessage messages and
	// dispatches them to the callback.
	handler := func(hdlrCtx context.Context, bMsg extensions.BrokerMessage) (bool, error) {
		// Try to convert the broker message to the expected type
		msg, err := brokerMessageToUserSignedUpMessage(bMsg)
		if err != nil {
			return false, nil
		}

		// Validate it against the message schema to discriminate it from the
		// other message types received on this channel.
		if err := validate.Struct(msg); err != nil {
			return false, nil
		}

		// Execute the subscription function
		if err := fn(hdlrCtx, msg); err != nil {
			return true, err
		}

		return true, nil
	}

	// Register the handler and subscribe to the channel if not done already
	return c.subscribeToReceiveEventsOperation(ctx, addr, "UserSignedUpMessage", handler)
}

// UnsubscribeFromReceiveEventsOperationForUserSignedUp will stop the reception of UserSignedUp messages from Events channel.
// The underlying broker subscription is canceled once the last message type on
// the channel is unsubscribed.
// A timeout can be set in context to avoid blocking operation, if needed.
func (c *AppController) UnsubscribeFromReceiveEventsOperationForUserSignedUp(
	ctx context.Context,
) {
	// Get channel address
	addr := "v3.issue333.events"

	c.unsubscribeFromReceiveEventsOperation(ctx, addr, "UserSignedUpMessage")
}

// subscribeToReceiveEventsOperation registers a per-message handler on the
// Events channel and, on the first
// registration, opens a single broker subscription multiplexed to every
// registered handler (issue #333).
func (c *AppController) subscribeToReceiveEventsOperation(
	ctx context.Context,
	addr string,
	msgName string,
	handler messageDispatchHandler,
) error {
	c.dispatcher.mutex.Lock()
	defer c.dispatcher.mutex.Unlock()

	// If there are already handlers on this channel, just register this one: the
	// existing broker subscription will dispatch to it.
	if handlers, exists := c.dispatcher.handlers[addr]; exists {
		if _, exists := handlers[msgName]; exists {
			err := fmt.Errorf("%w: controller is already subscribed for message %q on channel %q", extensions.ErrAlreadySubscribedChannel, msgName, addr)
			c.logger.Error(ctx, err.Error(), extensions.LogInfosFromContext(ctx)...)
			return err
		}

		handlers[msgName] = handler
		c.logger.Info(ctx, "Subscribed to channel", extensions.LogInfosFromContext(ctx)...)
		return nil
	}

	// First registration on this channel: register the handler...
	c.dispatcher.handlers[addr] = map[string]messageDispatchHandler{msgName: handler}

	// ...and subscribe to the broker channel.
	sub, err := c.broker.Subscribe(ctx, addr)
	if err != nil {
		delete(c.dispatcher.handlers, addr)
		c.logger.Error(ctx, err.Error(), extensions.LogInfosFromContext(ctx)...)
		return err
	}
	c.subscriptions[addr] = sub
	c.logger.Info(ctx, "Subscribed to channel", extensions.LogInfosFromContext(ctx)...)

	// Asynchronously listen to new messages and dispatch them to the matching
	// registered handler.
	go func() {
		for {
			// Listen to next message
			stop, err := c.listenToReceiveEventsOperationNextMessage(addr, sub)
			if err != nil {
				c.logger.Error(ctx, err.Error(), extensions.LogInfosFromContext(ctx)...)
			}

			// Stop if required
			if stop {
				return
			}
		}
	}()

	return nil
}

func (c *AppController) listenToReceiveEventsOperationNextMessage(
	addr string,
	sub extensions.BrokerChannelSubscription,
) (stop bool, err error) {
	// Create a context for the received response
	msgCtx, cancel := context.WithCancel(context.Background())
	msgCtx = addAppContextValues(msgCtx, addr)
	msgCtx = context.WithValue(msgCtx, extensions.ContextKeyIsDirection, "reception")
	defer cancel()

	// Wait for next message
	acknowledgeableBrokerMessage, open := <-sub.MessagesChannel()

	// If subscription is closed and there is no more message
	// (i.e. uninitialized message), then exit the function
	if !open && acknowledgeableBrokerMessage.IsUninitialized() {
		return true, nil
	}

	// Set broker message to context
	msgCtx = context.WithValue(msgCtx, extensions.ContextKeyIsBrokerMessage, acknowledgeableBrokerMessage.String())

	// Execute middlewares before handling the message
	if err := c.executeMiddlewares(msgCtx, &acknowledgeableBrokerMessage.BrokerMessage, func(middlewareCtx context.Context) error {
		// Snapshot the registered message names in a deterministic order
		c.dispatcher.mutex.Lock()
		handlers := c.dispatcher.handlers[addr]
		msgNames := make([]string, 0, len(handlers))
		for msgName := range handlers {
			msgNames = append(msgNames, msgName)
		}
		c.dispatcher.mutex.Unlock()
		sort.Strings(msgNames)

		// Try each registered handler until one matches the received message
		for _, msgName := range msgNames {
			c.dispatcher.mutex.Lock()
			handler := c.dispatcher.handlers[addr][msgName]
			c.dispatcher.mutex.Unlock()
			if handler == nil {
				continue
			}

			handled, err := handler(middlewareCtx, acknowledgeableBrokerMessage.BrokerMessage)
			if err != nil {
				return err
			}
			if handled {
				acknowledgeableBrokerMessage.Ack()
				return nil
			}
		}

		// No registered handler matched the received message
		return extensions.ErrNoMatchingMessage
	}); err != nil {
		c.errorHandler(msgCtx, addr, &acknowledgeableBrokerMessage, err)
		// On error execute the acknowledgeableBrokerMessage nack() function and
		// let the BrokerAcknowledgment decide what is the right nack behavior for the broker
		acknowledgeableBrokerMessage.Nak()
	}

	return false, nil
}

func (c *AppController) unsubscribeFromReceiveEventsOperation(
	ctx context.Context,
	addr string,
	msgName string,
) {
	c.dispatcher.mutex.Lock()
	defer c.dispatcher.mutex.Unlock()

	// Check if there are handlers for this channel
	handlers, exists := c.dispatcher.handlers[addr]
	if !exists {
		return
	}

	// Check if this message type is subscribed
	if _, exists := handlers[msgName]; !exists {
		return
	}

	// Remove the handler for this message type
	delete(handlers, msgName)

	// Set context
	ctx = addAppContextValues(ctx, addr)

	// If there are no more handlers on this channel, cancel the broker subscription
	if len(handlers) == 0 {
		delete(c.dispatcher.handlers, addr)

		if sub, exists := c.subscriptions[addr]; exists {
			sub.Cancel(ctx)
			delete(c.subscriptions, addr)
		}
	}

	c.logger.Info(ctx, "Unsubscribed from channel", extensions.LogInfosFromContext(ctx)...)
}

// UserController is the structure that provides sending capabilities to the
// developer and and connect the broker with the User
type UserController struct {
	controller
}

// NewUserController links the User to the broker
func NewUserController(bc extensions.BrokerController, options ...ControllerOption) (*UserController, error) {
	// Check if broker controller has been provided
	if bc == nil {
		return nil, extensions.ErrNilBrokerController
	}

	// Create default controller
	controller := controller{
		broker:        bc,
		subscriptions: make(map[string]extensions.BrokerChannelSubscription),
		logger:        extensions.DummyLogger{},
		middlewares:   make([]extensions.Middleware, 0),
		errorHandler:  extensions.DefaultErrorHandler(),
	}

	// Apply options
	for _, option := range options {
		option(&controller)
	}

	return &UserController{controller: controller}, nil
}

func (c UserController) wrapMiddlewares(
	middlewares []extensions.Middleware,
	callback extensions.NextMiddleware,
) func(ctx context.Context, msg *extensions.BrokerMessage) error {
	var called bool

	// If there is no more middleware
	if len(middlewares) == 0 {
		return func(ctx context.Context, msg *extensions.BrokerMessage) error {
			// Call the callback if it exists and it has not been called already
			if callback != nil && !called {
				called = true
				return callback(ctx)
			}

			// Nil can be returned, as the callback has already been called
			return nil
		}
	}

	// Get the next function to call from next middlewares or callback
	next := c.wrapMiddlewares(middlewares[1:], callback)

	// Wrap middleware into a check function that will call execute the middleware
	// and call the next wrapped middleware if the returned function has not been
	// called already
	return func(ctx context.Context, msg *extensions.BrokerMessage) error {
		// Call the middleware and the following if it has not been done already
		if !called {
			// Create the next call with the context and the message
			nextWithArgs := func(ctx context.Context) error {
				return next(ctx, msg)
			}

			// Call the middleware and register it as already called
			called = true
			if err := middlewares[0](ctx, msg, nextWithArgs); err != nil {
				return err
			}

			// If next has already been called in middleware, it should not be executed again
			return nextWithArgs(ctx)
		}

		// Nil can be returned, as the next middleware has already been called
		return nil
	}
}

func (c UserController) executeMiddlewares(ctx context.Context, msg *extensions.BrokerMessage, callback extensions.NextMiddleware) error {
	// Wrap middleware to have 'next' function when calling them
	wrapped := c.wrapMiddlewares(c.middlewares, callback)

	// Execute wrapped middlewares
	return wrapped(ctx, msg)
}

func addUserContextValues(ctx context.Context, addr string) context.Context {
	ctx = context.WithValue(ctx, extensions.ContextKeyIsVersion, "1.0.0")
	ctx = context.WithValue(ctx, extensions.ContextKeyIsProvider, "user")
	return context.WithValue(ctx, extensions.ContextKeyIsChannel, addr)
}

// Close will clean up any existing resources on the controller
func (c *UserController) Close(ctx context.Context) {
	// Unsubscribing remaining channels
}

// SendToReceiveEventsOperationForUserDeleted will send a UserDeleted message on Events channel.
func (c *UserController) SendToReceiveEventsOperationForUserDeleted(
	ctx context.Context,
	msg UserDeletedMessage,
) error {
	// Set channel address
	addr := "v3.issue333.events"

	// Set context
	ctx = addUserContextValues(ctx, addr)
	ctx = context.WithValue(ctx, extensions.ContextKeyIsDirection, "publication")

	// Convert to BrokerMessage
	brokerMsg, err := msg.toBrokerMessage()
	if err != nil {
		return err
	}

	// Set broker message to context
	ctx = context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, brokerMsg.String())

	// Send the message on event-broker through middlewares
	return c.executeMiddlewares(ctx, &brokerMsg, func(ctx context.Context) error {
		return c.broker.Publish(ctx, addr, brokerMsg)
	})
}

// SendToReceiveEventsOperationForUserSignedUp will send a UserSignedUp message on Events channel.
func (c *UserController) SendToReceiveEventsOperationForUserSignedUp(
	ctx context.Context,
	msg UserSignedUpMessage,
) error {
	// Set channel address
	addr := "v3.issue333.events"

	// Set context
	ctx = addUserContextValues(ctx, addr)
	ctx = context.WithValue(ctx, extensions.ContextKeyIsDirection, "publication")

	// Convert to BrokerMessage
	brokerMsg, err := msg.toBrokerMessage()
	if err != nil {
		return err
	}

	// Set broker message to context
	ctx = context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, brokerMsg.String())

	// Send the message on event-broker through middlewares
	return c.executeMiddlewares(ctx, &brokerMsg, func(ctx context.Context) error {
		return c.broker.Publish(ctx, addr, brokerMsg)
	})
}

// AsyncAPIVersion is the version of the used AsyncAPI document
const AsyncAPIVersion = "1.0.0"

// MessageWithCorrelationID is implemented by messages that carry a correlation ID.
type MessageWithCorrelationID interface {
	CorrelationID() string
	SetCorrelationID(id string)
}

// Error is the error structure returned by the controller operations.
type Error struct {
	Channel string
	Err     error
}

// Error returns a string representation of the error.
func (e *Error) Error() string {
	return fmt.Sprintf("channel %q: err %v", e.Channel, e.Err)
}

// Message 'UserDeletedMessageFromEventsChannel' reference another one at '#/components/messages/userDeleted'.
// This should be fixed in a future version to allow message override.
// If you encounter this message, feel free to open an issue on this subject
// to let know that you need this functionnality.

// Message 'UserSignedUpMessageFromEventsChannel' reference another one at '#/components/messages/userSignedUp'.
// This should be fixed in a future version to allow message override.
// If you encounter this message, feel free to open an issue on this subject
// to let know that you need this functionnality.

// UserDeletedMessagePayload is a schema from the AsyncAPI specification required in messages
type UserDeletedMessagePayload struct {
	Event string `json:"event" validate:"oneof='user_deleted'"`
	Id    string `json:"id"`
}

// UserDeletedMessage is the message expected for 'UserDeletedMessage' channel.
type UserDeletedMessage struct {
	// Payload will be inserted in the message payload
	Payload UserDeletedMessagePayload
}

// NewUserDeletedMessage creates a new UserDeletedMessage with default values if any.
func NewUserDeletedMessage() UserDeletedMessage {
	var msg UserDeletedMessage

	return msg
}

// brokerMessageToUserDeletedMessage will fill a new UserDeletedMessage with data from generic broker message
func brokerMessageToUserDeletedMessage(bMsg extensions.BrokerMessage) (UserDeletedMessage, error) {
	var msg UserDeletedMessage

	// Unmarshal payload to expected message payload format
	err := json.Unmarshal(bMsg.Payload, &msg.Payload)
	if err != nil {
		return msg, err
	}

	// TODO: run checks on msg type

	return msg, nil
}

// toBrokerMessage will generate a generic broker message from UserDeletedMessage data
func (msg UserDeletedMessage) toBrokerMessage() (extensions.BrokerMessage, error) {
	// TODO: implement checks on message

	// Marshal payload to JSON
	payload, err := json.Marshal(msg.Payload)
	if err != nil {
		return extensions.BrokerMessage{}, err
	}

	// There is no headers here
	headers := make(map[string][]byte, 0)

	return extensions.BrokerMessage{
		Headers: headers,
		Payload: payload,
	}, nil
}

// UserSignedUpMessagePayload is a schema from the AsyncAPI specification required in messages
type UserSignedUpMessagePayload struct {
	Event string `json:"event" validate:"oneof='user_signed_up'"`
	Id    string `json:"id"`
}

// UserSignedUpMessage is the message expected for 'UserSignedUpMessage' channel.
type UserSignedUpMessage struct {
	// Payload will be inserted in the message payload
	Payload UserSignedUpMessagePayload
}

// NewUserSignedUpMessage creates a new UserSignedUpMessage with default values if any.
func NewUserSignedUpMessage() UserSignedUpMessage {
	var msg UserSignedUpMessage

	return msg
}

// brokerMessageToUserSignedUpMessage will fill a new UserSignedUpMessage with data from generic broker message
func brokerMessageToUserSignedUpMessage(bMsg extensions.BrokerMessage) (UserSignedUpMessage, error) {
	var msg UserSignedUpMessage

	// Unmarshal payload to expected message payload format
	err := json.Unmarshal(bMsg.Payload, &msg.Payload)
	if err != nil {
		return msg, err
	}

	// TODO: run checks on msg type

	return msg, nil
}

// toBrokerMessage will generate a generic broker message from UserSignedUpMessage data
func (msg UserSignedUpMessage) toBrokerMessage() (extensions.BrokerMessage, error) {
	// TODO: implement checks on message

	// Marshal payload to JSON
	payload, err := json.Marshal(msg.Payload)
	if err != nil {
		return extensions.BrokerMessage{}, err
	}

	// There is no headers here
	headers := make(map[string][]byte, 0)

	return extensions.BrokerMessage{
		Headers: headers,
		Payload: payload,
	}, nil
}

const (
	// EventsChannelPath is the constant representing the 'EventsChannel' channel path.
	EventsChannelPath = "v3.issue333.events"
)

// ChannelsPaths is an array of all channels paths
var ChannelsPaths = []string{
	EventsChannelPath,
}
