// Package "issue211" provides primitives to interact with the AsyncAPI specification.
//
// Code generated by github.com/lerenn/asyncapi-codegen version (devel) DO NOT EDIT.
package issue211

import (
	"encoding/json"
	"fmt"

	"github.com/lerenn/asyncapi-codegen/pkg/extensions"
)

// AsyncAPIVersion is the version of the used AsyncAPI document
const AsyncAPIVersion = "0.1.0"

// MessageWithCorrelationID is implemented by messages that carry a correlation ID.
type MessageWithCorrelationID interface {
	CorrelationID() string
	SetCorrelationID(id string)
}

// Error is the error structure returned by the controller operations.
type Error struct {
	Channel string
	Err     error
}

// Error returns a string representation of the error.
func (e *Error) Error() string {
	return fmt.Sprintf("channel %q: err %v", e.Channel, e.Err)
}

// Message 'EventSuccessMessageMessageFromEventSuccessChannel' reference another one at '#/components/messages/EventSuccess'.
// This should be fixed in a future version to allow message override.
// If you encounter this message, feel free to open an issue on this subject
// to let know that you need this functionnality.

// EventSuccessMessagePayload is a schema from the AsyncAPI specification required in messages
type EventSuccessMessagePayload struct {
	// Description: The timestamp of the event
	Timestamp *int64 `json:"timestamp,omitempty"`
}

// EventSuccessMessage is the message expected for 'EventSuccessMessage' channel.
type EventSuccessMessage struct {
	// Payload will be inserted in the message payload
	Payload EventSuccessMessagePayload
}

// NewEventSuccessMessage creates a new EventSuccessMessage with default values if any.
func NewEventSuccessMessage() EventSuccessMessage {
	var msg EventSuccessMessage

	return msg
}

// brokerMessageToEventSuccessMessage will fill a new EventSuccessMessage with data from generic broker message
func brokerMessageToEventSuccessMessage(bMsg extensions.BrokerMessage) (EventSuccessMessage, error) {
	var msg EventSuccessMessage

	// Unmarshal payload to expected message payload format
	err := json.Unmarshal(bMsg.Payload, &msg.Payload)
	if err != nil {
		return msg, err
	}

	// TODO: run checks on msg type

	return msg, nil
}

// toBrokerMessage will generate a generic broker message from EventSuccessMessage data
func (msg EventSuccessMessage) toBrokerMessage() (extensions.BrokerMessage, error) {
	// TODO: implement checks on message

	// Marshal payload to JSON
	payload, err := json.Marshal(msg.Payload)
	if err != nil {
		return extensions.BrokerMessage{}, err
	}

	// There is no headers here
	headers := make(map[string][]byte, 0)

	return extensions.BrokerMessage{
		Headers: headers,
		Payload: payload,
	}, nil
}

const (
	// EventSuccessChannelPath is the constant representing the 'EventSuccessChannel' channel path.
	EventSuccessChannelPath = "v3.issue211.topic"
)

// ChannelsPaths is an array of all channels paths
var ChannelsPaths = []string{
	EventSuccessChannelPath,
}
