// Package "issue114" provides primitives to interact with the AsyncAPI specification.
//
// Code generated by github.com/lerenn/asyncapi-codegen version (devel) DO NOT EDIT.
package issue114

import (
	"fmt"

	"github.com/lerenn/asyncapi-codegen/pkg/extensions"
)

// AsyncAPIVersion is the version of the used AsyncAPI document
const AsyncAPIVersion = "1.2.3"

type MessageWithCorrelationID interface {
	CorrelationID() string
	SetCorrelationID(id string)
}

type Error struct {
	Channel string
	Err     error
}

func (e *Error) Error() string {
	return fmt.Sprintf("channel %q: err %v", e.Channel, e.Err)
}

// V2Issue114StatusMessage is the message expected for 'V2Issue114StatusMessage' channel.
type V2Issue114StatusMessage struct {
	// Payload will be inserted in the message payload
	Payload string
}

func NewV2Issue114StatusMessage() V2Issue114StatusMessage {
	var msg V2Issue114StatusMessage

	return msg
}

// brokerMessageToV2Issue114StatusMessage will fill a new V2Issue114StatusMessage with data from generic broker message
func brokerMessageToV2Issue114StatusMessage(bMsg extensions.BrokerMessage) (V2Issue114StatusMessage, error) {
	var msg V2Issue114StatusMessage

	// Convert to string
	payload := string(bMsg.Payload)
	msg.Payload = payload // No need for type conversion to reference

	// TODO: run checks on msg type

	return msg, nil
}

// toBrokerMessage will generate a generic broker message from V2Issue114StatusMessage data
func (msg V2Issue114StatusMessage) toBrokerMessage() (extensions.BrokerMessage, error) {
	// TODO: implement checks on message

	// Convert to []byte
	payload := []byte(msg.Payload)

	// There is no headers here
	headers := make(map[string][]byte, 0)

	return extensions.BrokerMessage{
		Headers: headers,
		Payload: payload,
	}, nil
}

const (
	// V2Issue114StatusPath is the constant representing the 'V2Issue114Status' channel path.
	V2Issue114StatusPath = "v2.issue114.status"
)

// ChannelsPaths is an array of all channels paths
var ChannelsPaths = []string{
	V2Issue114StatusPath,
}
